version: "3.8"

services:
  rabbitmq:
    container_name: events_rabbitmq
    image: rabbitmq:3.8.16-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_VHOST=/